apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  lables:
    a: b
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d61aba3942caf712
