apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  targetNamespace: wordpress
  releaseName: wordpress
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  chart:
    spec:
      chart: wordpress
      version: 15.2.22
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m    
  values:
    wordpressUsername: admin
    existingSecret: wordpress-admin-secret
    persistence:
      enabled: true
      existingClaim: wordpress-pvc
      accessModes:
      - ReadWriteMany
    volumePermissions:
      enabled: true
    resources:
      limits: 
        memory: 768Mi
        cpu: 300m
      requests: 
        memory: 512Mi
        cpu: 200m        
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql.dev.wordpress.uchicago.local
      port: 3306
      user: wordpress
      existingSecret: mysql-database-secret
      database: wordpress
    memcached:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
      resources:
        limits: 
          memory: 768Mi
          cpu: 300m
        requests: 
          memory: 512Mi
          cpu: 200m
