apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  targetNamespace: jenkins
  releaseName: jenkins
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  chart:
    spec:
      chart: jenkins
      version: 10.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m    
  values:
    
