---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: monitoring
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 30m0s
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/fluxcd/flux2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
      namespace: flux-system
  healthChecks:
  - kind: Deployment
    name: kube-prometheus-stack-operator
    namespace: monitoring
  - kind: Deployment
    name: kube-prometheus-stack-grafana
    namespace: monitoring
  interval: 1h0m0s
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  timeout: 2m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-stack
  interval: 1h0m0s
  path: ./manifests/monitoring/monitoring-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring

